# Generated by Django 3.1.2 on 2020-11-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hoodname',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
